# Generated by Django 4.1 on 2022-08-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descripton',
            new_name='description',
        ),
    ]
