# Generated by Django 4.1 on 2022-08-24 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_created',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='/static/images/profile_pictures/default.png', null=True, upload_to='blog/static/images/profile_pictures', verbose_name='تصویر')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=50, verbose_name='نام خانوادگی')),
                ('age', models.IntegerField(help_text='Enter your age', verbose_name='سن')),
                ('gender', models.CharField(blank=True, choices=[('female', 'خانم'), ('male', 'آقا')], max_length=10, null=True, verbose_name='جنسیت')),
                ('address', models.TextField(verbose_name=' آدرس')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'پروفایل کاربری',
                'verbose_name_plural': 'پروفایل کاربری',
            },
        ),
    ]
