# Generated by Django 4.1 on 2022-08-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='account/static/images/profile_pictures/default/default.png', null=True, upload_to='blog/static/images/profile_pictures', verbose_name='تصویر'),
        ),
    ]
