# Generated by Django 4.1 on 2022-08-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_options_customuser_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
