# Generated by Django 4.1 on 2022-08-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
    ]
