# Generated by Django 4.1 on 2022-08-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='account/static/images/profile_pictures/default.png', null=True, upload_to='blog/static/images/profile_pictures', verbose_name='تصویر'),
        ),
    ]
